management:
  security:
    enabled: false
spring:
    jpa:
      hibernate:
        ddl-auto: create
        generate-ddl: true
      show-sql: true
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 123
